In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
from google.colab import files

print('Please select the StudentsPerformance.csv file to upload:')
uploaded = files.upload()

Please select the StudentsPerformance.csv file to upload:

Saving StudentsPerformance.csv to StudentsPerformance (1).csv

In [17]:
data=pd.read_csv("StudentsPerformance.csv")
data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [18]:
data.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [20]:
data.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [22]:
x=data.drop("math score",axis=1)
y=data["math score"]

In [23]:
y

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

In [24]:
x

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,74
1,female,group C,some college,standard,completed,90,88
2,female,group B,master's degree,standard,none,95,93
3,male,group A,associate's degree,free/reduced,none,57,44
4,male,group C,some college,standard,none,78,75
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,99,95
996,male,group C,high school,free/reduced,none,55,55
997,female,group C,high school,free/reduced,completed,71,65
998,female,group D,some college,standard,completed,78,77
999,female,group D,some college,free/reduced,none,86,86

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.2,random_state=42
)

In [26]:
x_train

,gender,race/ethnicity,parental level of education,lunch,test preparation course,reading score,writing score
29,female,group D,master's degree,standard,none,70,75
535,female,group C,bachelor's degree,free/reduced,completed,83,83
695,female,group D,some college,free/reduced,none,89,86
557,male,group C,master's degree,free/reduced,none,67,66
836,male,group E,high school,standard,none,64,57
...,...,...,...,...,...,...,...
106,female,group D,master's degree,standard,none,100,100
270,male,group C,bachelor's degree,standard,none,63,61
860,female,group C,associate's degree,standard,none,62,53
435,male,group C,some college,free/reduced,completed,48,53
102,female,group D,associate's degree,standard,none,91,89

In [27]:
y_train

29     62
535    66
695    79
557    61
836    73
       ..
106    87
270    69
860    53
435    50
102    85
Name: math score, Length: 800, dtype: int64

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

In [56]:
num_cols=x.select_dtypes(include=[np.number]).columns
cat_cols=x.select_dtypes(include=["object"]).columns
preprocessor=ColumnTransformer([
    ("num",StandardScaler(),num_cols),
    ("cat",OneHotEncoder(),cat_cols)
]
)

In [36]:
preprocessor

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 Index(['reading score', 'writing score'], dtype='object')),
                                ('cat', OneHotEncoder(),
                                 Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course'],
      dtype='object'))])

In [37]:
from sklearn.linear_model import LinearRegression

In [39]:
from sklearn.pipeline import Pipeline
model=Pipeline([
    ("prep",preprocessor),
    ("reg",LinearRegression())
])
model.fit(x_train,y_train)

Pipeline(steps=[('prep',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  Index(['reading score', 'writing score'], dtype='object')),
                                                 ('cat', OneHotEncoder(),
                                                  Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course'],
      dtype='object'))])),
                ('reg', LinearRegression())])

In [41]:
preds = model.predict(x_test)
preds

array([76.3879697 , 58.88597004, 76.99026483, 76.85180448, 87.62737816,
       79.0140238 , 64.65460865, 53.00791885, 74.18471015, 49.21353815,
       52.94765047, 36.66906418, 67.9139255 , 52.27725558, 86.71848338,
       70.53070205, 51.95556639, 46.8314386 , 48.82375101, 52.72669531,
       73.88582984, 38.88612362, 57.38074421, 36.32839723, 78.14908978,
       81.79995075, 75.3849409 , 46.1184787 , 31.03596334, 49.90094972,
       65.98409138, 70.4116652 , 60.5061564 , 83.73986218, 84.43184961,
       46.07265627, 76.10135181, 70.20596817, 65.85782103,  3.76186106,
       78.49792748, 67.25291552, 67.97175998, 60.2734092 , 79.67385074,
       67.60005539, 72.24589185, 24.76000748, 85.95581153, 70.08842684,
       75.41268803, 66.79864565, 81.16502181, 45.6635254 , 66.11051928,
       67.32545668, 86.13600492, 58.72739768, 82.23614367, 81.21768838,
       47.23421792, 72.04512129, 70.64302698, 55.92646405, 86.31798368,
       63.86663678, 59.48657443, 55.91061249, 57.20534331, 82.14529335,
       71.7699997 , 80.48800131, 58.37254249, 46.38271551, 61.23110052,
       85.00868631, 84.24763549, 60.29504754, 59.29079503, 53.21863924,
       63.67390126, 41.11157129, 78.88214466, 66.84103064, 75.31833494,
       54.83981972, 67.15234837, 63.82189712, 75.52303569, 25.62821483,
       73.94825388, 93.73515048, 62.58770738, 75.59475675, 29.38699024,
       70.73386967, 66.93187334, 61.92556713, 65.55791118, 55.20177526,
       75.58525549, 65.95258762, 60.78523045, 58.22323456, 73.69255355,
       69.03108155, 53.43168552, 79.78812987, 69.95962427, 48.24398402,
       34.75888574, 73.57987373, 61.02255528, 55.44111787, 76.06527502,
       62.30119887, 50.03966166, 50.41456346, 72.47871292, 78.5740347 ,
       59.65296718, 53.46106773, 86.88463283, 63.62352914, 60.48911247,
       69.56999884, 67.61786834, 65.95349122, 48.91443961, 72.2650211 ,
       74.04028673, 76.00676728, 45.18827584, 88.2500252 , 63.41762788,
       33.49612649, 77.41830126, 80.67922222, 73.64586103, 39.17339666,
       49.59104603, 59.64985162, 58.94567985, 53.90806788, 77.58246012,
       46.96198062, 43.09459912, 76.52721488, 57.24860962, 79.21480841,
       74.99715605, 76.2557111 , 65.66853346, 59.54629188, 84.86974981,
       73.3355475 , 43.8021998 , 62.85429878, 75.93245533, 51.92100812,
       62.03949307, 65.03337151, 70.28496267, 53.88034365, 89.12694975,
       70.96403647, 49.52051633, 92.67984324, 60.67159844, 72.1160923 ,
       83.08768858, 79.12026636, 80.44677214, 69.87534158, 57.47299365,
       23.71788008, 59.19704574, 64.835207  , 91.76004359, 67.11752378,
       61.52335861, 59.86061451, 81.91071454, 60.129492  , 93.33460827,
       68.30759036, 63.21362158, 58.57367017, 71.1787559 , 89.12325804,
       52.72500029, 61.19295573, 66.97539131, 65.70059223, 54.11620448,
       43.40914918, 62.15221448, 67.88839463, 67.0222873 , 62.34513246])

In [43]:
y_test

521    91
737    53
740    80
660    74
411    84
       ..
408    52
332    62
208    74
613    65
78     61
Name: math score, Length: 200, dtype: int64

In [46]:
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, preds)
rmse = np.sqrt(mse)
print(rmse)

5.393993869732841

In [47]:
students = [
    {
        "gender": "male",
        "race/ethnicity": "group C",
        "parental level of education": "high school",
        "lunch": "free/reduced",
        "test preparation course": "none",
        "reading score": 60,
        "writing score": 58
    },
    {
        "gender": "female",
        "race/ethnicity": "group A",
        "parental level of education": "master's degree",
        "lunch": "standard",
        "test preparation course": "completed",
        "reading score": 88,
        "writing score": 90
    }
]

df = pd.DataFrame(students)
preds = model.predict(df)

for i, p in enumerate(preds):
    print(f"Student {i+1} predicted math score: {p:.2f}")

Student 1 predicted math score: 61.91
Student 2 predicted math score: 77.14

In [50]:
import joblib

joblib.dump(model, 'student_model.pkl')

model = joblib.load('student_model.pkl')

In [60]:
print("Enter student details:")

gender = input("Gender (male/female): ")
race = input("Race/Ethnicity (group A/B/C/D/E): ")
parent_edu = input("Parental education (some high school/high school/some college/associate\'s degree/bachelor\'s degree/master\'s degree): ")
lunch = input("Lunch (standard or free/reduced): ")
prep = input("Test preparation (completed/none): ")

reading = int(input("Reading score: "))
writing = int(input("Writing score: "))


student = {
    "gender": gender,
    "race/ethnicity": race,
    "parental level of education": parent_edu,
    "lunch": lunch,
    "test preparation course": prep,
    "reading score": reading,
    "writing score": writing
}

student_df = pd.DataFrame([student])
prediction = model.predict(student_df)
print("Predicted Math Score:", round(prediction[0], 2))

Enter student details:
Gender (male/female): male
Race/Ethnicity (group A/B/C/D/E): group A
Parental education (some high school/high school/some college/associate's degree/bachelor's degree/master's degree): some college
Lunch (standard or free/reduced): standard
Test preparation (completed/none): none
Reading score: 90
Writing score: 90
Predicted Math Score: 96.37